Please use this Google doc to code during your interview. To free your hands for coding, we recommend that you use a headset or a phone with speaker option.

Description: Write the “scream” function. Given a string as input, perform the following transformation - for each letter in the string with n occurrences, substitute each occurrence with n^2 repetitions of that letter. Return the result in all capital letters.

Examples:
Banana -> BAAAAAAAAANNNNAAAAAAAAANNNNAAAAAAAAA
Aardvark -> AAAAAAAAAAAAAAAAAARRRRDVAAAAAAAAARRRRK

function scream(s) {
	const count = {};
	s = s.toUpperCase();

	for (let i=0; i<s.length; i++) {
  	if (count[s[i]]) {
  		count[s[i]]++;
    } else {
  	  count[s[i]] = 1;
    }
  }

  let res = ‘’;
  for (let i=0; i<s.length; i++) {
  	res += s[i].repeat(count[s[i]]*count[s[i]]);
  }
  return res;
}


Follow up: Write the “unscream” function. Given a string generated by “scream” as input, transform the string back into its original format - reduce the letter counts appropriately and return in lowercase.

Examples:
BAAAAAAAAANNNNAAAAAAAAANNNNAAAAAAAAA -> banana

baaa Baaaaaaaaaaaaa  27  = 3 * 3^2
aaaa  4*4^2 = 64






function unscream(s) {
	const count = {};
	for (let i=0; i<s.length; i++) {
  	if (count[s[i]]) {
  		count[s[i]]++;
    } else {
    	count[s[i]] = 1;
    }
  }

  for (let char in count) {
  	let num = Math.pow(count[char],1/3);
  	count[char] = num;
  }

  let res = ‘’;
  let idx = 0;

  while (idx < s.length) {
  	res += s[idx];
  	let num = count[s[idx]];
  	idx += num*num;
  }

  return res.toLowerCase();
}
